FROM python:3.7


# RUN pip install fastapi

# COPY . /usr/src/app
# CMD ["python", "server/main.py"]
# RUN pip install paho-mqtt &&\
#     pip install fastapi &&\
#     pip install pydantic &&\
# RUN pip install -r requirements.txt
# CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
# CMD [ "python", "main.py" ]


COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

